"""Update users and create history

Revision ID: 196b0eb94cb6
Revises: 723f56f681d4
Create Date: 2025-11-29 15:33:45.577039

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "196b0eb94cb6"
down_revision: Union[str, Sequence[str], None] = "723f56f681d4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "history_messages",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("id_user", sa.UUID(), nullable=False),
        sa.Column("message_text", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id_user"],
            ["users.id"],
            name=op.f("fk_history_messages_id_user_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_history_messages")),
    )
    op.create_table(
        "message_gpts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("message_user", sa.Text(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_message_gpts_user_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_message_gpts")),
    )
    op.add_column(
        "users",
        sa.Column("chat_disabled", sa.Integer(), nullable=False, server_default="0"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "chat_disabled")
    op.drop_table("message_gpts")
    op.drop_table("history_messages")
    # ### end Alembic commands ###
